version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  app:
    image: python-backend
    environment:
      DB_NAME: app_db
      DB_USER: root
      DB_PASSWORD: 12345
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "5001:5000"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
